AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order API using Lambda with API Gateway

Parameters:
  Stage:
   Type: String
   Default: prod
   Description: StageName of API Gateway

Globals:
  Function:
    Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    CodeUri: build/function.zip
    Runtime: java21
    MemorySize: 256
    Timeout: 15
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-users"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: web-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - https://hercis-www.s3.mx-central-1.amazonaws.com/order/index.html
        - http://localhost:5173
      LogoutURLs:
        - https://hercis-www.s3.mx-central-1.amazonaws.com
        - http://localhost:5173
      PreventUserExistenceErrors: ENABLED

  CognitoDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${AWS::StackName}-auth"
      UserPoolId: !Ref CognitoUserPool
      ManagedLoginVersion: "2"

  OrderApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: Order Backend API
      Auth:
        DefaultAuthorizer: CognitoAuth
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Accept,Authorization,Origin'"
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"

  OrderBackend:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: createOrder
          ORDER_TABLE_NAME: !Ref OrderTable
      MemorySize: 256
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref OrderTable
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApiGateway
            Path: /{proxy+}
            Method: ANY
            Auth:
              Authorizer: CognitoAuth

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Order"
#      TableName: Order
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  OrderBackendApi:
    Description: API Gateway endpoint URL for application
    Value: !Sub 'https://${OrderApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/'
    Export:
      Name: OrderBackendApi